export const DestinationsCards = [
  {
    id: 1,
    title: "Area:",
    description: "Talas",
    variant: "DestinationsCard",
    tours: 11,
    img: "/images/images2.svg",
  },
  {
    id: 2,
    title: "Area:",
    description: "Talas",
    variant: "DestinationsCard",
    tours: 12,
    img: "/images/images2.svg",
  },
  {
    id: 3,
    title: "Area:",
    description: "Talas",
    variant: "DestinationsCard",
    img: "/images/images2.svg",
  },
  {
    id: 4,
    title: "Area:",
    description: "Talas",
    variant: "DestinationsCard",
    tours: 13,
    img: "/images/images2.svg",
  },
  {
    id: 5,
    title: "Area:",
    description: "Talas",
    variant: "DestinationsCard",
    tours: 14,
    img: "/images/images2.svg",
  },
  {
    id: 6,
    title: "Area:",
    description: "Talas",
    variant: "DestinationsCard",
    tours: 15,
    img: "/images/images2.svg",
  },
];
