export const tourButtons = [
    {title : "Tour class", id:1,filter : [
        {name : "Most popular",id: 1, index:false},
        {name : "Trekking",id: 2, index:false},
        {name : "Multi - active",id: 3, index:false},
        {name : "Horse riding",id: 4, index:false},
        {name : "Winter tours",id: 5, index:false},
        {name : "Moto trip",id: 6, index:false},
        {name : "Cultural",id: 7, index:false},
        {name : "Road trip",id: 8, index:false},
        {name : "Horse riding",id: 9, index:false},
    ]},
    {title : "Places i want to visit",id:2,filter : [
        {name : "Cholpon - Ata",id: 1, index:false},
        {name : "Bosteri",id: 2, index:false},
        {name : "Ala - Archa",id: 3, index:false},
        {name : "San - Tash",id: 4, index:false},
        {name : "Akbulung",id: 5, index:false},
        {name : "Batken",id: 6, index:false},
        {name : "Bokonbay",id: 7, index:false},
        {name : "Saimaluu - Tash",id: 8, index:false},
        {name : "Kochkor",id: 9, index:false},
        {name : "Arslanbob",id: 10, index:false},
        {name : "Talas",id: 11, index:false},
        {name : "Jalal - Abad",id: 12, index:false},
        {name : "Karakol",id: 13, index:false},
        {name : "Issik - Kol lake",id: 14, index:false},
        {name : "Naryn town",id: 15, index:false},
        {name : "Sary - Chelek lake",id: 16, index:false},
        {name : "Osh town",id: 17, index:false},
        {name : "Bishkek",id: 18, index:false},
        {name : "Tash - Rabat Caravanserai",id: 19, index:false},
        {name : "Song - kol lake",id: 20, index:false},
        {name : "Kel - Suu lake",id: 21, index:false},
    ]},
    {title : "Activities",id:3,filter : [
        {name : "Backpacking",id: 1, index:false},
        {name : "Base Camp",id: 2, index:false},
        {name : "Canoe",id: 3, index:false},
        {name : "Rafting",id: 4, index:false},
        {name : "Packraft",id: 5, index:false},
        {name : "Horses",id: 6, index:false},
        {name : "Photography",id: 7, index:false},
        {name : "Custom",id: 8, index:false},
    ]},
    {title : "Duration",id:4,filter : [
        {name : "1 day",id: 1, index:false},
        {name : "2 days",id: 2, index:false},
        {name : "3 days",id: 3, index:false},
        {name : "4 days",id: 4, index:false},
        {name : "5 days",id: 5, index:false},
        {name : "6 days",id: 6, index:false},
        {name : "7 days",id: 7, index:false},
        {name : "8 days",id: 8, index:false},
        {name : "9 days",id: 9, index:false},
        {name : "10 days",id: 10, index:false},
        {name : "11 days",id: 11, index:false},
        {name : "12 days",id: 12, index:false},
        {name : "13 days",id: 13, index:false},
        {name : "14 days",id: 14, index:false},
        {name : "15 days",id: 15, index:false},
        {name : "16 days",id: 16, index:false}
    ]}
]